# Generated by Django 6.1 on 2026-09-01 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gated_society',
            field=models.ForeignKey(blank=True, db_column='gated_society_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='societies.gatedsociety'),
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='auth.group'),
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
