"""add resident profile and guardian link

Revision ID: ac5895124525
Revises: 36c186439552
Create Date: 2026-08-25 23:45:30.902206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5895124525'
down_revision: Union[str, Sequence[str], None] = '36c186439552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardian_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('resident_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Enum('primary', 'secondary', name='guardian_priority_enum'), nullable=False),
    sa.Column('consent_status', sa.Enum('pending', 'accepted', 'declined', name='consent_status_enum'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('guardian_id != resident_id', name='ck_guardian_not_self'),
    sa.ForeignKeyConstraint(['guardian_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guardian_id', 'resident_id', name='uq_guardian_resident_pair')
    )
    op.create_index('uq_one_primary_guardian_per_resident', 'guardian_links', ['resident_id'], unique=True, postgresql_where=sa.text("priority = 'primary'"))
    op.create_table('resident_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('flat_id', sa.UUID(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'away', 'deactivated', name='resident_status_enum'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resident_profiles')
    op.drop_index('uq_one_primary_guardian_per_resident', table_name='guardian_links', postgresql_where=sa.text("priority = 'primary'"))
    op.drop_table('guardian_links')
    op.execute("DROP TYPE IF EXISTS guardian_priority_enum CASCADE;")
    op.execute("DROP TYPE IF EXISTS consent_status_enum CASCADE;")
    op.execute("DROP TYPE IF EXISTS resident_status_enum CASCADE;")
    # ### end Alembic commands ###
