"""add nearby_neighbours jsonb column to resident_profiles

Revision ID: e1da71710ac1
Revises: 16846ba40474
Create Date: 2026-08-26 08:42:05.210737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1da71710ac1'
down_revision: Union[str, Sequence[str], None] = '16846ba40474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resident_profiles', sa.Column('nearby_neighbours', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resident_profiles', 'nearby_neighbours')
    # ### end Alembic commands ###
