# Generated by Django 6.1 on 2026-09-01 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GatedSociety',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('in_charge', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_admin', models.ForeignKey(blank=True, db_column='sub_admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_societies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gated Society',
                'verbose_name_plural': 'Gated Societies',
                'db_table': 'gated_society',
                'ordering': ['-created_at'],
            },
        ),
    ]
